"""empty message

Revision ID: 7edffa04a6ea
Revises: 7145fc106bdb
Create Date: 2017-05-16 11:02:09.407328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edffa04a6ea'
down_revision = '7145fc106bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'username')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
